### PR TITLE
Fix config handling, provide poll interval

### LINKED ISSUE #75: Frequent refresh too CPU intensive
Vole _checks for new posts every second_.
This is a very _CPU intensive task_ and there's no need to check once a second.
So I suggest changing this line:
    static/js/vole.js:        setTimeout(refreshUI, 1000);
increasing refresh time, for example to 5 or 10 seconds.

### PR DESCRIPTION
**Pull request by marktheunissen**
Fixes https://github.com/vole/vole/issues/75

### CODE REVIEW

File: static/js/vole.js [hunk 1]
```diff
@@ -9,6 +9,23 @@
...
+      App.voleConfig = data;
+    }
+    else {
+      throw new Error('Unable to fetch config information.');
+    }
+  }).fail(function(jqXHR, textStatus) {
+    throw new Error("Request for config failed: " + textStatus);
+  });
+
+  //-------------------------
```
Comment (pifantastic) [inline static/js/vole.js]: Is this a race condition? How can we be sure the config has been fetched before we reference it in `setTimeout`?

File: src/lib/config/config.go [hunk 2]
```diff
@@ -13,30 +12,34 @@ type Config struct {
...
+  config.UI.Reverse = false
+  config.UI.PollInterval = 3000
+  config.Server.Listen = "127.0.0.1:6789"
+  config.Server.Debug = false
 
+  // Now read config.json for any overrides of the defaults.
   var file []byte
   file, err := ioutil.ReadFile("config.json")
-  if err != nil {
-    file, err = ioutil.ReadFile("config.sample.json")
```
Comment (marktheunissen) [inline src/lib/config/config.go]: Don't read the config.sample.json file anymore, that was a mistake, because people could edit it. Rather bake in the values so the app doesn't fail.

**Comment by pifantastic** [comment]
This looks good to me (aside from the one comment). I like getting rid of the sample config file.

File: static/js/vole.js (hunk 1 above)
Comment (marktheunissen) [inline static/js/vole.js]: The first poll is hardcoded to happen after 5s, so the config will be available. However I can put a check in to make sure it's not undefined.

Comment (pifantastic) [inline static/js/vole.js]: Cool. A check is good for now. Another thought is to serve the config as part of the HTML so we can be certain it's available without having to make an ajax call.

**Comment by marktheunissen** [comment]
@ilario Are you sure you're running the latest code? The backend doesn't read config.sample.json anymore. It has the default values compiled in. It will attempt to read config.json if it exists, and any value in there will override the default.

**Comment by ilario** [comment]
You were right, I'm sorry, it was my fault (I was using old code due to a mistake in my launcher).

**Comment by marktheunissen** [comment]
Great, glad it's working for you.
